# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pyserial(object):
    def setupUi(self, pyserial):
        pyserial.setObjectName("pyserial")
        pyserial.resize(851, 701)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pyserial.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(pyserial)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.s1__box_1 = QtWidgets.QPushButton(self.groupBox)
        self.s1__box_1.setObjectName("s1__box_1")
        self.horizontalLayout.addWidget(self.s1__box_1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.horizontalLayout_2.addWidget(self.s1__box_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.state_label = QtWidgets.QLabel(self.groupBox)
        self.state_label.setText("")
        self.state_label.setObjectName("state_label")
        self.horizontalLayout_8.addWidget(self.state_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.horizontalLayout_3.addWidget(self.s1__box_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.horizontalLayout_4.addWidget(self.s1__box_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.s1__box_5 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.horizontalLayout_5.addWidget(self.s1__box_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.s1__box_6 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.horizontalLayout_6.addWidget(self.s1__box_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_button = QtWidgets.QPushButton(self.groupBox)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_7.addWidget(self.open_button)
        self.close_button = QtWidgets.QPushButton(self.groupBox)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_7.addWidget(self.close_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 9, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ztlb = QtWidgets.QLabel(self.groupBox)
        self.ztlb.setObjectName("ztlb")
        self.horizontalLayout_9.addWidget(self.ztlb)
        self.zhuangtai = QtWidgets.QLabel(self.groupBox)
        self.zhuangtai.setText("")
        self.zhuangtai.setObjectName("zhuangtai")
        self.horizontalLayout_9.addWidget(self.zhuangtai)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 10, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 0, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.groupBox_3)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.gridLayout_5.addWidget(self.s2__receive_text, 0, 0, 1, 5)
        self.hex_receive = QtWidgets.QCheckBox(self.groupBox_3)
        self.hex_receive.setObjectName("hex_receive")
        self.gridLayout_5.addWidget(self.hex_receive, 1, 0, 1, 1)
        self.s2__clear_button = QtWidgets.QPushButton(self.groupBox_3)
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.gridLayout_5.addWidget(self.s2__clear_button, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(348, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hex_send = QtWidgets.QCheckBox(self.groupBox_4)
        self.hex_send.setObjectName("hex_send")
        self.gridLayout_3.addWidget(self.hex_send, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 1, 1, 1)
        self.s3__send_text = QtWidgets.QTextEdit(self.groupBox_4)
        self.s3__send_text.setObjectName("s3__send_text")
        self.gridLayout_3.addWidget(self.s3__send_text, 0, 0, 1, 8)
        self.s3__clear_button = QtWidgets.QPushButton(self.groupBox_4)
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.gridLayout_3.addWidget(self.s3__clear_button, 1, 3, 1, 1)
        self.timer_send_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.gridLayout_3.addWidget(self.timer_send_cb, 1, 4, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setMaxLength(3276)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 6, 1, 1)
        self.s3__send_button = QtWidgets.QPushButton(self.groupBox_4)
        self.s3__send_button.setObjectName("s3__send_button")
        self.gridLayout_3.addWidget(self.s3__send_button, 1, 7, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        pyserial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pyserial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 22))
        self.menubar.setObjectName("menubar")
        pyserial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pyserial)
        self.statusbar.setObjectName("statusbar")
        pyserial.setStatusBar(self.statusbar)

        self.retranslateUi(pyserial)
        QtCore.QMetaObject.connectSlotsByName(pyserial)

    def retranslateUi(self, pyserial):
        _translate = QtCore.QCoreApplication.translate
        pyserial.setWindowTitle(_translate("pyserial", "pyserial"))
        self.groupBox.setTitle(_translate("pyserial", "串口设置"))
        self.label_7.setText(_translate("pyserial", "先检测并选择串口"))
        self.label_8.setText(_translate("pyserial", "再打开串口！"))
        self.label.setText(_translate("pyserial", "串口检测："))
        self.s1__box_1.setText(_translate("pyserial", "检测串口"))
        self.label_2.setText(_translate("pyserial", "串口选择："))
        self.label_13.setText(_translate("pyserial", "串口："))
        self.label_3.setText(_translate("pyserial", "波特率："))
        self.s1__box_3.setItemText(0, _translate("pyserial", "115200"))
        self.s1__box_3.setItemText(1, _translate("pyserial", "2400"))
        self.s1__box_3.setItemText(2, _translate("pyserial", "4800"))
        self.s1__box_3.setItemText(3, _translate("pyserial", "9600"))
        self.s1__box_3.setItemText(4, _translate("pyserial", "12800"))
        self.s1__box_3.setItemText(5, _translate("pyserial", "14400"))
        self.s1__box_3.setItemText(6, _translate("pyserial", "19200"))
        self.s1__box_3.setItemText(7, _translate("pyserial", "38400"))
        self.s1__box_3.setItemText(8, _translate("pyserial", "57600"))
        self.s1__box_3.setItemText(9, _translate("pyserial", "76800"))
        self.s1__box_3.setItemText(10, _translate("pyserial", "230400"))
        self.s1__box_3.setItemText(11, _translate("pyserial", "460800"))
        self.label_4.setText(_translate("pyserial", "数据位："))
        self.s1__box_4.setItemText(0, _translate("pyserial", "8"))
        self.s1__box_4.setItemText(1, _translate("pyserial", "5"))
        self.s1__box_4.setItemText(2, _translate("pyserial", "6"))
        self.s1__box_4.setItemText(3, _translate("pyserial", "7"))
        self.label_6.setText(_translate("pyserial", "校验位："))
        self.s1__box_5.setItemText(0, _translate("pyserial", "N"))
        self.label_5.setText(_translate("pyserial", "停止位："))
        self.s1__box_6.setItemText(0, _translate("pyserial", "1"))
        self.open_button.setText(_translate("pyserial", "打开串口"))
        self.close_button.setText(_translate("pyserial", "关闭串口"))
        self.ztlb.setText(_translate("pyserial", "串口状态："))
        self.label_12.setText(_translate("pyserial", "QT5,python3设计"))
        self.groupBox_3.setTitle(_translate("pyserial", "接收区"))
        self.hex_receive.setText(_translate("pyserial", "Hex接收"))
        self.s2__clear_button.setText(_translate("pyserial", "清除"))
        self.label_9.setText(_translate("pyserial", "已接收："))
        self.groupBox_4.setTitle(_translate("pyserial", "接收区"))
        self.hex_send.setText(_translate("pyserial", "Hex发送"))
        self.label_10.setText(_translate("pyserial", "已发送："))
        self.s3__send_text.setHtml(_translate("pyserial", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123456</p></body></html>"))
        self.s3__clear_button.setText(_translate("pyserial", "清除"))
        self.timer_send_cb.setText(_translate("pyserial", "定时发送"))
        self.lineEdit_3.setText(_translate("pyserial", "1000"))
        self.label_11.setText(_translate("pyserial", "ms/次"))
        self.s3__send_button.setText(_translate("pyserial", "发送"))

import icons_rc
